//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_NETEntityFramework
{
    using System;
    
    public enum ColorNames : int
    {
        Red = 0,
        Blue = 1,
        Green = 2,
        Orange = 3,
        Yellow = 4,
        Purple = 5,
        Pink = 6,
        Black = 7,
        White = 8
    }
}
