//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_NETEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFavourites
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string FavoriteNumber { get; set; }
        public ColorNames FavoriteColor { get; set; }
        public string Birthday { get; set; }
    }
}
